pluginManagement {
    repositories {
        gradlePluginPortal()
        maven { url = 'https://maven.minecraftforge.net' }
        maven { url = 'https://maven.parchmentmc.org' }
        maven { url = 'https://repo.spongepowered.org/repository/maven-public/' }
    }
}

dependencyResolutionManagement { repositoriesMode = RepositoriesMode.PREFER_PROJECT }

rootProject.name = 'BlastTravel-Forge-1.20.1'
